services:
  web-meeting-calendar-php:
    build:
      context: .
    container_name: web-meeting-calendar-service
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: web-meeting-calendar-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: usermongodb
      MONGO_INITDB_ROOT_PASSWORD: passwordmongodb
      MONGO_INITDB_DATABASE: mycalendarmongodb
    ports:
      - "23568:27017"
    volumes:
      - web-meeting-calendar-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: web-meeting-calendar-postgresql
    restart: always
    environment:
      POSTGRES_USER: userpostgre
      POSTGRES_PASSWORD: passwordpostgre
      POSTGRES_DB: mycalendarpostgredb

    ports:
      - "5556:5432"
    volumes:
      - web-meeting-calendar-postgresql:/data/db/postgresql

volumes:
  web-meeting-calendar-mongodb:
    driver: local
  web-meeting-calendar-postgresql:
    driver: local
